### ISSUE TITLE
Question related to image shake

### ISSUE THREAD

**Issue by vcshing** [waynegm/imgViewer2#10]
Hello. 
i found that for some cases, the image will be shaked after initial the photo.
the number of transform: translate(0px, 0px); will be keep update even if no any action.

it may be cause by the width and height is very big for the original photo.
how can i fixed it?

eg.
http://gogogo.synology.me/imgviewer2/imgViewer2.html
open at ie

**Comment by waynegm** [comment]
Can't see any image at your link - so an unable to see your problem. 

Something you could you try is replacing:
`$(document).ready(function() {`
with
`$(window).on("load,function() {`
This will ensure the image is loaded and the display size has been determined before attaching the viewer.

**Comment by vcshing** [comment]
you cannot see the image at my link is due to my image format is TIF. and it do not support at Firefox or chrome. it should open at IE browser.

I changed the image to JPEG format. you can see the image at the same link at any browser now.
http://gogogo.synology.me/imgviewer2/imgViewer2.html

the same problem is exist even change to "load" event.

**Comment by vcshing** [comment]
Dear Eric,
Thank you for the reply.
I changed Math.round to Math.floor,
but the problem seem still exist.
thank you for your help

**Comment by Eric-Guo** [comment]
Yes, it seems much hard than I expected, I try another place (vTop = with round/floor), also disable zoom and draggable, seems both no use.

**Comment by waynegm** [comment]
From what I can see this is a problem inside Leaflet. A workaround is to explicitly set the zoom level in a custom onReady callback.
'''
$(window).on("load",function() {
    var $img = $("#image1").imgViewer2({
                           onReady: function() {
                               this.setZoom(1);
                           }
    });
});
'''
Note you will need to use the imgViewer2  in the master branch which now includes a fix to setZoom to catch when the maxZoom option is undefined.

**Comment by vcshing** [comment]
After i updated the plugin and set the zoom level in a custom onReady callback.
the problem is almost fixed.
but after i drag the image, the problem will be happen again.
but i think it may acceptable,
thank you for your support.

**Comment by Eric-Guo** [comment]
When just browsing files, large images look good now, but if I zoom out completely, the shaking is still visible. http://recordit.co/xfdo70MjzB

But I think setZoom help a little.

```javascript
$("#img-previewer").imgViewer2({ onReady: function() { this.setZoom(1.001);}});
```

**Comment by waynegm** [comment]
Doing a
'''
this.setZoom(2);
this.setZoom(1);
'''
in an onReady callback eliminates the shaking completely for me. No shaking if I drag the image after it loads. If that seems too much of a hack you could have a look at my [imgViewer](https://github.com/waynegm/imgViewer) plugin.
