### ISSUE TITLE
Issue with Large Image 

### ISSUE THREAD

**Issue by RajnikPatel** [waynegm/imgViewer2#13]
I face issue when image is large.
**Note :** I face issue only in iPad and iPhone only.
Resolution : 4320 x 7680
Size : 2.15 MB
When image is load in plugin half image display proper and half image display gray.
When I remove **.imgViewer2()** image fully load problem is only with **imgViewer2** plugin.

![img_0774](https://user-images.githubusercontent.com/36290487/36016201-dd78d2ca-0d97-11e8-8b37-7cdf6360fc90.PNG)

Please give me a solution.

**Comment by waynegm** [comment]
This maybe related to this Leaflet issue [5895](https://github.com/Leaflet/Leaflet/issues/5895). They suggest disabling 3D acceleration (set global switch L_DISABLE_3D to true before loading Leaflet) as a work around:
```
<script>L_DISABLE_3D = true;</script>
<script` src="leaflet.js"></script>
```
I can't test this as I don't have access to an iPad/iPhone and the Google Chrome emulator for iPad/iPhone doesn't show this problem. Can you try this and let me know the outcome.

**Comment by RajnikPatel** [comment]
No.
It's still not work

**Comment by waynegm** [comment]
You could try different versions of Leaflet to see if that makes a difference. Other than that it may be an iOS limitation for which I can't offer any help or workaround. Would it be worth giving my [imgViewer](https://github.com/waynegm/imgViewer) plugin a try which doesn't use Leaflet?

**Comment by RajnikPatel** [comment]
For this your solution.
how I can remove gray color background of image ?
In this solution image will loaded full but background behavior not good. 
```
<script>L_DISABLE_3D = true;</script>
<script` src="leaflet.js"></script>
```

**Comment by waynegm** [comment]
Use CSS to change the background color. Include the following (change the ddd to the hex color you want) into your site CSS and load it after leaflet.css
```
.leaflet-container {
	background: #ddd;
}
```
Is the minus button issue just with iPhone/iPad also?

**Comment by RajnikPatel** [comment]
No, minus button issue for all devices

**Comment by waynegm** [comment]
Can you provide a url demonstrating the issue so I can have a look at the code in a debugger?
