### ISSUE TITLE
Feature Request: Zoom to Width

### ISSUE THREAD

**Issue by imagremlin** [waynegm/imgViewer2#14]
When the image displayed does not match the aspect ratio of the viewer, it displays grey pillars or bands, which is a reasonable behaviour. 

![capture](https://user-images.githubusercontent.com/236134/36070746-a7ee63b2-0f55-11e8-9fc4-ec0269bfe2af.PNG)

When the image is initially loaded, I need it to be zoomed in such a way that the grey borders are not visible

![capture2](https://user-images.githubusercontent.com/236134/36070772-181142d6-0f56-11e8-81eb-ce64661bd5ec.PNG)

How can I determine the required level of zoom? Could this be a built in function? (should probably zoom to height if the image aspect ratio is wider than the viewer)

**Comment by waynegm** [comment]
There is an option called "constraint" that may do what you want. It should be given either the value "width" or "height". Then have an onReady callback defined that does a setZoom(1) as per the little example below. Using the constraint: 'width' would give you want you are after for images narrower than the viewport. The grey pillars will become visible if the image is panned. There is no built in way of preventing that.
```
(function($) {
    $(window).on("load", function() {
        var $img = $("#image1").imgViewer2({
            constraint: 'width',
            onReady: function() {
                this.setZoom(1);
            }
        });
    });
})(jQuery);
```
