### ISSUE TITLE
Question - Convert x,y pixels to google lat,long

### ISSUE THREAD

**Issue by softsan** [waynegm/imgViewer2#15]
Hi I am using this plugin and its really do the job nicely. 
Is it possible to  convert x,y pixel in my db to lat, long of google map ?

I need this because i want to render my custom map to google map and for that i need lat, long  instead of x,y pixel position.

Thanks.

**Comment by waynegm** [comment]
You need to know the lat,long of the image corners and if you that why not just georeference the image in QGIS?
