### ISSUE TITLE
Problems with marker popups near the top border

### ISSUE THREAD

**Issue by imagremlin** [waynegm/imgViewer2#17]
Hi 

If a marker is added close to the top border, it is impossible to see the popup. 

For example, if you modify the sample at

https://waynegm.github.io/imgViewer2/basic_note.html

Like so (I've moved one of the markers to the top), you can see the problem. 

`$(document).ready( function() {
var $img = $("#image1").imgNotes2({
onReady: function() {
var notes = [	{x: "0.5", y:"0.5", note:"AFL Grand Final Trophy"}, 
				{x: "0.322", y:"0.1", note: '\
					<center><b>Brisbane Lions Flag</b><br/>\
					<img src="http://www.lions.com.au/static-resources/themes/brisbane/images/logo-brisbane.png"/></center>\
					<a href="http://www.lions.com.au/" target="blank">The Brisbane Lions</a> \
					is an <a href="http://en.wikipedia.org/wiki/Australian_rules_football" target="blank">Australian rules football club.</a>'
				},
				{x: "0.824", y: "0.593", note: "Fluffy microphone"}];
		this.import(notes);
	}
});
});
})(jQuery);`

How can I get around this?

**Comment by waynegm** [comment]
There are Leaflet plugins that provide better popup handling. One of the [examples](https://waynegm.github.io/imgViewer2/basic_note_with_plugins.html) provide a demonstration of the [Leaflet Responsive Popup plugin](https://github.com/yafred/leaflet-responsive-popup) which does just what you want.

**Comment by imagremlin** [comment]
Thanks, that worked perfectly
