### ISSUE TITLE
Set the minimum height 

### ISSUE THREAD

**Issue by dave7777** [waynegm/imgViewer2#22]
Hello,
I tried to modiy the dynamic size image file with this code and it still schrinsk the whole picture -

	<img  id="image1" src="chartsimageview/docs/images/1.png" width="100%" min-height="500px"/>

can you please help?
Dave

**Comment by waynegm** [comment]
Recommend you read up on [applying CSS](https://www.w3schools.com/html/html_css.asp). For inline CSS you use the style attribute:
```
style="width: 100%; min-height: 500px;"
```

**Comment by dave7777** [comment]
thank you for your kind reply:)
