### ISSUE TITLE
Can we rotate image of imgViewer  on 90 degree ?

### ISSUE THREAD

**Issue by ankit-vaghela** [waynegm/imgViewer2#23]
I want to rotate image of imgViewer on 90 degree.

**Comment by waynegm** [comment]
Why not just rotate the image offline and send it?
Otherwise have a look at the available [Leaflet Plugins](http://leafletjs.com/plugins.html) maybe there is one that does what you want.

**Comment by ankit-vaghela** [comment]
I try that. I rotate image to 90 degree but issue is my marker get change. Because when I use first time I use image at 0 degree. And I want to fit image in map overlay so I need to rotate it 90 degree. So I think I need to rotate map to 90 degree. Is there any way that I can rotate leaflet map to 90 degree ?

**Comment by waynegm** [comment]
Could you swap the x and y coordinates of the markers (may need a sign change as well depending on if the rotation is clockwise or not) then they would plot correctly.

**Comment by ankit-vaghela** [comment]
I am sending sample code on your email. I think then you can get me. Thanks
