### ISSUE TITLE
Forcing Image Reload

### ISSUE THREAD

**Issue by dave7777** [waynegm/imgViewer2#24]
Hello
I noticed the script does not reload the image if it was already _**cashed**_ - can I somehow force the script to reload the image each time the page is reloaded?
Thansk a lot!!!
Dave

**Comment by waynegm** [comment]
I think you will find that it is a [browser cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) issue. Ctrl+F5 will force a page load to bypass the cache on most browsers or if you open the developer tools and do a page reload the cache will be bypassed as well.

**Comment by dave7777** [comment]
Thank you dear Wayne - do you think there is away to force the image to be reloaded each time  by using the ajavascript code itselt? I mean can it be doen by addign soem code inside the imageviewer js file?
thanks a lot!)

**Comment by waynegm** [comment]
It is possible to force a reload of an image by adding a query string to the image url. Commonly people add the current time:
```
imgurl += new Date().getTime();
```
If you want to force a reload of the entire html page from the server use:
```
location.reload(true);
```

**Comment by dave7777** [comment]
Thank you so much for helping me out Waye....

I have this code in the html page

	
				<div align="center">
					<img  id="image1" src="chartsimageview/docs/images/INTEX-weekly-trendlines-chart.png" style="width: 100%; min-height: 400px;"/>

can you help me add that code to this image link..... I tried it this way:

<div align="center">
					<img  id="image1" src="chartsimageview/docs/images/INTEX-weekly-trendlines-chart.png+= new Date().getTime();" style="width: 100%; min-height: 400px;"/>
				</div>

and it did not work:(((

**Comment by dave7777** [comment]
I guess it shoudl be like this:

> <div align="center">
> 					<img  id="image1" src="chartsimageview/docs/images/INTEX-weekly-trendlines-chart.png"+= new Date().getTime(); style="width: 100%; min-height: 400px;"/>
> 				</div>

illiterate me)

**Comment by waynegm** [comment]
Try this combination:
```
<img id="image1" class="NOCACHE" src="chartsimageview/docs/images/INTEX-weekly-trendlines-chart.png style="width: 100%; min-height: 400px;"/>
```
Then have somewhere:
```
<script type="text/javascript">
    ;(function($) {
        $(document).ready(function () {           
            $('.NOCACHE').attr('src',function () { return $(this).attr('src') + "?a=" + new Date().getTime() });
         });
        $(window).on("load", function() {
            var $img = $("#image1").imgViewer2();
         });
    })(jQuery);
</script>
```

**Comment by dave7777** [comment]
interestign...let me try

**Comment by dave7777** [comment]
fantastic!!!! it works but with still loads the earleir version of the images for a split second when I use this code you kindly game me previously to zoom and pan into an image (I placed it at the start of imViewer.js  , at line 9):

```

$(document).ready( function() {
    var $img = $("#image1").imgViewer2({
       onReady: function() {
            this.setZoom(1.5).panTo(0.8,0.5);
        }
    });
});
```

When I removed the above code from the imViewer.js it workds fine - reloads the page withe the new image.....Can you please take a short look Wayne?

**Comment by dave7777** [comment]
This error of showing the previosu image before loading the new one persists in CHROME. :((((

**Comment by waynegm** [comment]
As shown in my example you should put the code that attaches the imgViewer2 plugin to the image in a $(window).on("load" callback. You should only be attaching the plugin once to an image so remove the other instances in the $(document).ready callbacks. I'd suggest you tidy up your code so it is all in a single <script> section at the end of the html page body. This will make the code logic much clearer and prevent issues  with repeating plugin declarations.

**Comment by dave7777** [comment]
I guess it should be reloadign image infinitely but in CHROME it only reloads it once or twice and them just keeps the image....

**Comment by dave7777** [comment]
the image name is Network tab in Chrome is:
chartsimageview/docs/images/INTEX-hourly-impulse-chart.png?a=1521473414052

**Comment by waynegm** [comment]
This screenshot shows it working for me with Chrome. Each browser refresh results in a GET request to the server with a unique query string. If I remove the class="NOCACHE" from the img element then there is a single GET to the server to fetch the image and subsequent page reloads use the browser cached image file and no GET request for the image is sent to the server. By comparison Firefox doesn't appear to store images in its browser cache as GET requests for the image are  made for each reload with or without including the class="NOCACHE" on the img element. 
![image](https://user-images.githubusercontent.com/3080502/37648982-38ec6c04-2c7c-11e8-9d88-be64cd332484.png)

**Comment by dave7777** [comment]
thank you for testign this for me - you tried changign the image and reloading it in th epage (I mean the web version of the page) in static - local versions all works perfectly....in web versions it doe snto work for me:(

**Comment by waynegm** [comment]
I ran it against a simple local web server. If you are using a production web server there may be server side caching going on. From your image name it sounds like it will be changing once a month. Have you considered including the image generation date actually as part of the image file name and updating the html page accordingly.  Then when the image changed it would have a different name and the web server and browser would be forced to GET the image and not rely on their caches and you wouldn't need to bother with the query string approach.

**Comment by dave7777** [comment]
thank you for your kind reply and tryign to help me Wayne.,...there are clsoe to 700 images, high resolutuin whhich will be regenerated daily so I need it to reald them fersh each time they are uploaded....I was givent hsi code by a friend which I use to fresh-load iframes (I need them to be updated simialrly to images)


```
 <div class="iframe-container">
           
             
           
           <iframe id="secondPage" height="1380" width="1110" frameborder="0" scrolling="no"> </iframe>
           
           <script>
			   
			   	var d = null;
  var iframe = null;
  d= new Date();
  var unique = d.getTime();
  
	iframe = $('#firstPage');
	iframe.attr('src','https://www.ubs.com/global/en.html?g='+unique);
  
  unique++;
	iframe = $('#secondPage');
	iframe.attr('src','https://www.ubs.com/global/en.html?g='+unique);
  
/*  unique++;
	iframe = $('#thirdPage');
	iframe.attr('src','https://www.ubs.com/global/en.html?g='+unique);*/

			  </script>
```
         

This code works in most browsers but it is made for iframes - can it be updated for images?? maybe because ti uses **g=** at the end of the url?

```
<script type="text/javascript">
    ;(function($) {
        $(document).ready(function () {           
            $('.NOCACHE').attr('src',function () { return $(this).attr('src') + "?a=" + new Date().getTime() });
         });
        $(window).on("load", function() {
            var $img = $("#image1").imgViewer2();
         });
    })(jQuery);
</script>
```

**Comment by waynegm** [comment]
The character or word between the "?" and the "=" is not significant, what is after the "?" just needs to be different. Brower's don't cache html pages as aggressively as images which is why the iframe code updates. There are some server settings that adjust the html headers to include hints to the browser about caching but they are not guaranteed to work. A Google search should turn information of those settings up.
I think the solution where you include a date-time string in the image name will be the best solution. Since you are generating so many images at such a frequent interval I presume that the process is somehow automated by some program code. You can extend that to give the images unique names. If the file name changes the browser will have to bypass the cache.

**Comment by dave7777** [comment]
hello Wayne...yes the images are generateds by MAtlab - I can surely append date names to the images but how do I spoecify such dynamic image file name in the html code itself? each image is shoqn ina  separate html page with its nmame specified in the code....do you think this can be implemeneted with the variable image name?

**Comment by waynegm** [comment]
If the html page is not too complex you could also write the html page with the updated file name using Matlab when you output the file. Otherwise you could pass the image file name in a query string and use javascript to update the image in the html page. Both those strategies should work.

**Comment by dave7777** [comment]
I see - thank you....I will try one of these approaches when I launch the project..

**Comment by dave7777** [comment]
Hello Wayne - hope yuou are doing fine.
I wanted to ask if you think this coe can be used along with your script to refresh the image after it was updated in teh server - to bypass the cache?

<img id="firstPage" </img>


<script>

    var d = null;
    var iframe = null;
    d= new Date();
    var unique = d.getTime();

    img = $('#firstPage');
    img.attr('src','http://www.morganstanley.com/pub/content/dam/msdotcom/ideas/china-belt-and-road/china-belt-and-road.jpg?g='+unique);

</script>
