### ISSUE TITLE
Refreshing image

### ISSUE THREAD

**Issue by dave7777** [waynegm/imgViewer2#25]
Hello Wayne - hope you are doing fine.
I wanted to ask if you think this code can be used along with your script to refresh the image after it was updated in the server - to bypass the cache?

```
<img id="firstPage" </img>


<script>

    var d = null;
    var iframe = null;
    d= new Date();
    var unique = d.getTime();

    img = $('#firstPage');
    img.attr('src','http://www.morganstanley.com/pub/content/dam/msdotcom/ideas/china-belt-and-road/china-belt-and-road.jpg?g='+unique);

</script>
```

**Comment by waynegm** [comment]
This is just a variation of the query string approach I suggested as a solution in the other issue thread but which you said wasn't working all the time.
In your code I'm not sure whether an <img></img> tag without a "src=" will be accepted by all browsers. Note you will need to attach the imgViewer2 to the image (in a "window.on('load'" callback) after the "img.attr" line. Give it a try - but if the query string approach wasn't working for you before, possibly because of server side caching, then I wouldn't expect this modified version of essentially the same approach will make a difference.

**Comment by dave7777** [comment]
Thank you Wayne 

Can you please check this code? I tried addign this randomizer to your script but it gives and error:

```
<script type="text/javascript">
	
	
    var d = null;
    d= new Date();
    var unique = d.getTime();
	
			;(function($) {
				$(document).ready(function() {
					var $img = $("#image1?g='+unique").imgViewer2();
				});
			})(jQuery);
		</script>
```

**Comment by waynegm** [comment]
The querystring should be added to the image src attribute not the image id attribute.
```
<script type="text/javascript">
 ;(function($) {
        $(document).ready(function () { 
            var unique = new Date().getTime();          
            $("#image1").attr("src",function () { return $(this).attr("src") + "?g=" + unique });
         });
        $(window).on("load", function() {
            var $img = $("#image1").imgViewer2();
         });
})(jQuery);
</script>
```

**Comment by dave7777** [comment]
Thank you dear Wayne for your kind help - this script appears to not work as the previosu versions - when I try the earleir approach in anothe rpage (without the imageviewer code) the file REFUSES TO LOAD IN OFFLINE mode:


<img id="firstPage" </img>


<script>

    var d = null;
    var iframe = null;
    d= new Date();
    var unique = d.getTime();

    img = $('#firstPage');
    img.attr('src','http://www.morganstanley.com/pub/content/dam/msdotcom/ideas/china-belt-and-road/china-belt-and-road.jpg?g='+unique);

</script>


But with this latest version of this script the image **still loads in offline mode...**. Please  let me know why this mitgh be the case - can your master script still cashe the iimages???

**Comment by waynegm** [comment]
I think your "img" tag needs a "src=" attribute and the "</img" is not required. So you need something like this in the html markup:
```
<img id="firstpage" src="http://www.morganstanley.com/pub/content/dam/msdotcom/ideas/china-belt-and-road/china-belt-and-road.jpg" >
```
You should also specify a width or height in there as well.

**Comment by dave7777** [comment]
Thank you dear Wayne for your continuous support) It shoudl look like this?

```

           <div class="row2">
           
           <table cellspacing="0" cellpadding="0" border="0" style="width: 100%">
			<tr>
			<td style="padding-left: 20px; padding-right: 20px ;padding-top: 5px;">
				
				<div align="center">
					<img id="firstpage" src="http://www.morganstanley.com/pub/content/dam/msdotcom/ideas/china-belt-and-road/china-belt-and-road.jpg" style="width: 100%; min-height: 400px;"/>
				</div>
				
			</td>
			</tr>
		</table>

<script type="text/javascript">
 ;(function($) {
        $(document).ready(function () { 
            var unique = new Date().getTime();          
            $("#image1").attr("src",function () { return $(this).attr("src") + "?g=" + unique });
         });
        $(window).on("load", function() {
            var $img = $("#image1").imgViewer2();
         });
})(jQuery);
</script>
```


this does not seem to work(

**Comment by waynegm** [comment]
Your "img" tag has an id of "firstpage" but your javascript is operating on "#image1". Change "#image1" to "#firstpage" in the 2 places it occurs and all will be well.
