### ISSUE TITLE
Positioning the plugin

### ISSUE THREAD

**Issue by shivanit2** [waynegm/imgViewer2#26]
I wanted to position the plugin on the top right of the modal instead of top left .How should I enable the leaflet-right class ?

**Comment by waynegm** [comment]
The plugin puts a div element over the orignal image which mimics the image's size and position. The plugin attaches Leaflet to the div and loads a copy of the image. I'd expect you just need to position the image where you want it via css/markup and attach the plugin to it.

**Comment by shivanit2** [comment]
Thank you for the response!Yes,I know I can position it through css. But just wanted to know if there was any other better way to do so in js. :)
