### ISSUE TITLE
imgViewer2 : replace "img" with DIV?

### ISSUE THREAD

**Issue by Salitehkat** [waynegm/imgViewer2#27]
Hi, this plugin id great, really fits lots of needs. 
In my case I need to be able to give all the functionalities to a DIV instead of to a "img". Do you think that is possible? I need to zoom, pan ect.. a SVG on top of a separated background (not svg but an image) all wrapped in a single DIV (hope i am able to explain well). 

Thanks so much for your work and attention. 

Sali.

**Comment by waynegm** [comment]
Have a look at the [Version_2](https://github.com/waynegm/imgViewer2/tree/Version_2) branch of the GitHub repository. This attaches the plugin to a DIV and might be a good starting point for what you are trying to do. Leaflet can display SVG directly. Have a look at the [multiple_image](https://github.com/waynegm/imgViewer2/blob/Version_2/docs/multiple_image.html) for some ideas.

**Comment by Salitehkat** [comment]
Thanks for answering. Ill have a deep look before any questions and bothering. Thanks again.

**Comment by Salitehkat** [comment]
Hi, 
After a lot of searching and testing ive decided to use this approach [multiple_image ](https://github.com/waynegm/imgViewer2/blob/Version_2/docs/multiple_image.html) instead of leaflet by itself as my project is more design oriented (with some map features like zoom, panning and overlaying layers) but using images. (its like a zooming interactive image) and ImgViewer is like this. So thanks for this plugin. Obviously I am not a developer and I know little of java. In resume I have a bitmap image as background, on top a svg and on top various animated gifs. I need to be able to syle each gif (position, size ect..). The best approach would be to load these gifs in a dynamically created DIV attached to the main DIv (imgv)? And then style this new div? Any light would be super appreciated it. 
Thanks a lot for your time and excuse if my questions are out of place.

**Comment by waynegm** [comment]
So as you zoom or pan about you want the svg and gifs appear to stay fixed
to the background image?

**Comment by Salitehkat** [comment]
Yes, bitmap layer, svg layer and gifs layers, all together. (attached to the main imgv div, which has the pan and zoom functions).  Thanks a lot.

**Comment by Salitehkat** [comment]
ps, it would be super if these 3 are appended as divs to the main div (imgv) instead as images so i can give them css style (easier for me). thanks again.

**Comment by waynegm** [comment]
I think the way to do this would be to add the base bitmap layer and the
svg layer as Leaflet imageOverlay layers and I would put the individual
gifs into permanently displayed Leaflet tooltips. By using appropriate
markup in the tooltip contents you will be able to style the contents by
css class. The way to do this is to extend the plugin as shown in some of
the examples.
Regards,
Wayne Mogg

**Comment by Salitehkat** [comment]
Good! ill try that and come back with results.  Thanks!!

**Comment by meathuldas010** [comment]
Is there any way to select an image by default? So, I can Zoom in or Zoom Out the image using Keyboard "+" or "-" Keys rather than using a mouse. Is it possible?

**Comment by waynegm** [comment]
You just need to give the widget the focus then it will interpret key strokes as per the default behavior of Leaflet. 
					var $img = $("#image1").imgViewer2();
					$img.data("wgmImgViewer2").view.focus();

**Comment by meathuldas010** [comment]
How to use this plugin for a multiple image gallery, I want to use the plugin properties for multiple images at a time. Is this possible? 
var $img = $(".image").imgViewer2(); 
Like giving a common class property
