### ISSUE TITLE
Individual markers demo

### ISSUE THREAD

**Issue by Jams02** [waynegm/imgViewer2#29]
Hi Wayne, thanks for the superb plugin!

Is it possible to provide an example that displays two or more different markers on the same image rather than the same style of markers? Currently trying to modify the example 'basic_note_with_plugins.html' to add a set of my own bespoke marker icons but with no success.

Any help really appreciated.

**Comment by waynegm** [comment]
Thanks, have a look at the attached file. If you want to know more about adding icons to Leaflet have a look at [this](https://leafletjs.com/examples/custom-icons/).
[test_variable_icons.zip](https://github.com/waynegm/imgViewer2/files/2194753/test_variable_icons.zip)

**Comment by Jams02** [comment]
Superb, really appreciate that Wayne, exactly what I needed!

Many thanks.

**Comment by waynegm** [comment]
OK
