### ISSUE TITLE
Add Number or Plain Text to Each Marker

### ISSUE THREAD

**Issue by bsoldiers** [waynegm/imgViewer2#32]
Hi Wayne, can we add number or just text to each marker? i would like to add them for categorizing, like pic i made with photoshop below

![marker-with-number](https://user-images.githubusercontent.com/37533602/50556490-3ca92f00-0d0c-11e9-89c5-ffc1f622cabb.jpg)

Thanks Wayne
Awesome Project 👍

**Comment by waynegm** [comment]
You have at least the following options:

- Add a [Leaflet DivIcon](https://leafletjs.com/reference-1.4.0.html#divicon), eg
```
var myIcon = L.divIcon({ className: 'my-div-icon', html: data.label});
var marker = L.marker(loc, {icon: myIcon}).addTo(map).bindPopup(data.note+"</br><input type='button' value='Delete' class='marker-delete-button'/>");
```
assuming data.label contains the text/number for the icon and using css style of my-div-icon

- If you use the [Beautify Marker plugin](https://github.com/marslan390/BeautifyMarker) then specify the text in the option string at creation, eg
```
options = {
          isAlphaNumericIcon: true,
          text: data.label,
          iconShape: 'marker',
          borderColor: '#00ABDC',
          textColor: '#00ABDC'
        };
var marker = L.marker(loc, {icon: L.BeautifyIcon.icon(options)}).addTo(map).bindPopup(data.note+"</br><input type='button' value='Delete' class='marker-delete-button'/>");
```
