### ISSUE TITLE
Fullscreen popup

### ISSUE THREAD

**Issue by fannarf** [waynegm/imgViewer2#33]
Hi Wayne 
First i want to thank you for this awesome project! 

Second i wanted to ask if it possible to open the popup assigned to the marker in fullscreen ? 
So the popup would more or less fill the whole map ? 

Regards
Fannar

**Comment by waynegm** [comment]
Leaflet popups have a class ".leaflet-popup-content". You can use that selector inside the popupopen event handler for a marker to modify the popup  appearance eg to change the width:
 					$(".leaflet-popup-content").width(500);

**Comment by fannarf** [comment]
Thanks for quick reply , this would only set the width of the popup to 500px right ? 
Is there away to open it so the width and possibly height is 100% of the map size (fullscreen) ?

Fannar

**Comment by waynegm** [comment]
Easiest solution would be to not use Leaflet popups (because their size and positioning is hard to control) and instead create your own div element in response to a marker click event. Following shows how a modified addNote method from the basicNote.html example would look.  
````
addNote: function(data) {
    var map = this.map,
          view = this.view,
          loc = this.relposToLatLng(data.x, data.y);
    var myIcon = L.divIcon({ className: 'my-div-icon', html: data.label});
    var marker = L.marker(loc, {icon: myIcon}).addTo(map);
    marker.on("click", function() {
        var temp = this;
        map.removeControl(map.zoomControl);
        var popup = $("<div class='mypopup' />").appendTo(view);
        $(".mypopup").css({
                                     position: "absolute",
                                     top: "0px",
                                     left: "0px",
                                     width: view.width()-6,
                                     height: view.height()-6,
                                     zIndex: 1100,
                                     backgroundColor: "white",
                                     border: "3px solid blue"
                                 });
        popup.html(data.note+"</br><input type='button' value='Close' class='popup-close-button'/>");
        $(".popup-close-button").click(function () {
            map.addControl(map.zoomControl);
	    popup.remove();
         });
    });
}
````

**Comment by fannarf** [comment]
Thanks again Wayne , sounds like a good work around but i can't get it to work .

I tried adding this to the basic_note.html example but it's not working (the marker is not being added )

<script type="text/javascript">
;(function($) {
/*
 *	Here we extend the imgViewer widget to display markers and notes
 *
 * This can be done with a few lines of code because of the capabilities of Leaflet
*/
	$.widget("wgm.imgNotes2", $.wgm.imgViewer2, {
		options: {
/*
 *	Default action for addNote callback
*/
addNote: function(data) {
    var map = this.map,
          view = this.view,
          loc = this.relposToLatLng(data.x, data.y);
    var myIcon = L.divIcon({ className: 'my-div-icon', html: data.label});
    var marker = L.marker(loc, {icon: myIcon}).addTo(map);
    marker.on("click", function() {
        var temp = this;
        map.removeControl(map.zoomControl);
        var popup = $("<div class='mypopup' />").appendTo(view);
        $(".mypopup").css({
                                     position: "absolute",
                                     top: "0px",
                                     left: "0px",
                                     width: view.width()-6,
                                     height: view.height()-6,
                                     zIndex: 1100,
                                     backgroundColor: "white",
                                     border: "3px solid blue"
                                 });
        popup.html(data.note+"</br><input type='button' value='Close' class='popup-close-button'/>");
        $(".popup-close-button").click(function () {
            map.addControl(map.zoomControl);
	    popup.remove();
         });
    });
},
		
/*
 *	Add notes from a javascript array
 */
		import: function(notes) {
			if (this.ready) {
				var self = this;
				$.each(notes, function() {
					self.options.addNote.call(self, this);
				});	
			}
		}
	});
	$(document).ready( function() {
		var $img = $("#image1").imgNotes2({
						onReady: function() {
							var notes = [	{x: "0.5", y:"0.5", note:"AFL Grand Final Trophy"}, 
											{x: "0.322", y:"0.269", note: '\
												<center><b>Brisbane Lions Flag</b><br/>\
												<img src="http://www.lions.com.au/static-resources/themes/brisbane/images/logo-brisbane.png"/></center>\
												<a href="http://www.lions.com.au/" target="blank">The Brisbane Lions</a> \
												is an <a href="http://en.wikipedia.org/wiki/Australian_rules_football" target="blank">Australian rules football club.</a>'
											},
											{x: "0.824", y: "0.593", note: "Fluffy microphone"}];
							this.import(notes);
						}
					});
	});
})(jQuery);
</script>

**Comment by waynegm** [comment]
Here is a complete working example, looks like you are missing the css style for the markers.
[test.zip](https://github.com/waynegm/imgViewer2/files/3197297/test.zip)

**Comment by fannarf** [comment]
Thank you so much Wayne! work like a charm.
