### ISSUE TITLE
Disabling plus minus zoom buttons

### ISSUE THREAD

**Issue by pmeran** [waynegm/imgViewer2#34]
Hi Wayne,

is there a way to get rid of the plus minus zoom buttons ?
They are certainly useful, but they don't look good on screenshots which are important in one of my projects.

Would be great if you could point me to the related lines of code.

Regards,
Paul

**Comment by waynegm** [comment]
You get the Leaflet map instance by calling the getMap method eg:
````
var map = $img.imgNotes2('getMap');
````
Then you can manipulate it based on the [Leaflet docs](https://leafletjs.com/reference-1.5.0.html). Something like:
````
map.zoomControl.remove();
````
should do the trick.

**Comment by pmeran** [comment]
Hi Wayne,

I got rid of the zoom Control by inserting

self.map = L.map($view.attr('id'), {zoomControl: false, ...

Thanks for your help !

Paul
