### ISSUE TITLE
setZoom in conflict with browser zoom ?

### ISSUE THREAD

**Issue by pmeran** [waynegm/imgViewer2#35]
Hi Wayne,

I am having issues with setZoom in some instances.

Here is a simplified version of the problem:
Self-assigning the zoom level of an image to itself (using onClick and setZoom) works fine (i.e. the image remains the same size). But as soon as I change the zoom level of the entire browser window (holding ctrl + mouse wheel), clicking on the image creates strange jumps in its zoom level.

All this is part of a project to evaluate multiple microsopy images - see code below. The same group of cells is depicted by two high-res images, one showing nuclei and the other a cellular protein. I use imgViewer2 to zoom around and pan in the first image, then I assign the zoom level and position to the other image.
This works actually well - unless I play with that browser zoom... which is kind of important though.
See sample code & images below, img path must be changed of course.

Two minor points:
1.
The only way I was able to apply setZoom to an image is using onClick. Can you please drop a line of code about how to apply setZoom through a click button ? I tried hard, to no avail.

2. I found a related post about syncing imgViewer for two images. This would also be a nice functionality for my project. But for a couple reasons I decided to go for the above implementation (and besides, I wasn't able to get your sample code for syncing to run - great if you have time to help with that too but for now solving that zoom conflict is more important).

Regards,
Paul

![021](https://user-images.githubusercontent.com/28399959/62818008-3c201480-baf5-11e9-810f-b9c9daacdc4b.gif)
![022](https://user-images.githubusercontent.com/28399959/62818009-43472280-baf5-11e9-9a57-ae6058854b6d.gif)

`	<body>

        <div class="layout" style="white-space: nowrap">
            <div id="row1" class="row">
                <div id="frame21" style="width: 260px; height: 200px; position: relative; overflow: hidden; display:inline-block;"><img id="image21" src="./img/021.gif" height="200px"></div>
                <div id="frame22" style="width: 260px; height: 200px; position: relative; overflow: hidden; display:inline-block;"><img id="image22" src="./img/022.gif" height="200px"></div>
            </div>
        </div>"

        <script type="text/javascript">

            var $img21 = $("#frame21");
            var $img22 = $("#frame22");   
            $img21.imgViewer2();
            $img22.imgViewer2();        

            var z1 = 1.0;
            var v1 = [0,0,1,1];
            var p1 = [0.5000, 0.5000];
        
            $img21.imgViewer2("option", "onClick", function() {
                z1 = this.getZoom();
                v1 = this.getView();

                m_x = (v1.left + v1.right)/2;
                m_y = (v1.top + v1.bottom)/2;
                p1 = [m_x, m_y];
                this.setZoom(z1);
                this.panTo(p1[0], p1[1]);

            });
            $img22.imgViewer2("option", "onClick", function() {
                this.setZoom(z1);
                this.panTo(p1[0], p1[1]);
            });

        </script>

	</body>`

**Comment by waynegm** [comment]
Have a look at the attached file (you will need to change the image src urls) which syncs the zoom and view even with dynamically sized images. It also works with browser zoom provided you don't change the browser zoom after manipulating the image. Unfortunately handling changes in the browser zoom is browser specific and I'm not aware of a reliable cross platform solution. Is there an alternative way of presenting your information so that the browser zoom isn't required.
 
[test_35.zip](https://github.com/waynegm/imgViewer2/files/3488706/test_35.zip)

**Comment by pmeran** [comment]
Hi Wayne,

the test file definitely works !

The final implementation I have in mind looks like this:
a grid of high-res images, with 4 columns (4 microscopy channels) and something like 10-50 rows (different specimens), where imgViewer2 zoom & pan is synced only to images in the same row.

The application would be a lot more useful with some sort of grid zoom (i.e. zooming on the entire grid, without changing individual images' zoom levels). It doesn't have to be browser zoom - I don't mind how it's implemented.

A few thoughts:
1.
I am not building an application for the web, it's for my own use (and our lab's). Getting it to work with google Chrome would be sufficient.
2.
Why Javascript if it's not for the web ? I thought about Matlab (don't like the licensing), or Python, but my feeling is that achieving interactivity with those platforms requires a lot of work.
3.
I could add group zoom by displaying images at varying size, selectable via buttons/toggles. Is html5 canvas an option ? If going for browser zoom in chrome, is there a particular method of function I need to focus on ?

Maybe you can point me in a direction.

Regards,
Paul

**Comment by waynegm** [comment]
How about displaying your page of images without imgViewer2 attached, you can use browser zoom freely to select image rows for detailed examination. A click on a row opens a popup window with the 4 images in a 2X2 grid with responsive (% based image sizes) with imgViewer2 attached. Maybe add some navigation buttons to scroll between rows without  returning to the big image grid. Another option for the detailed image display would be to overlay the 4 images and use a layer control to switch between them.

**Comment by pmeran** [comment]
Lots of ideas - not sure what I'm going to try next but thanks for the suggestions !
Very best,
Paul
