### ISSUE TITLE
Update marker position every 1 sec

### ISSUE THREAD

**Issue by anubhaw2091** [waynegm/imgViewer2#6]
I tried the plugin, I have a use case in which I need to update the marker every 1 sec.
`($(document).ready( function() {
		var $img = $("#image1").imgNotes2( {
						onReady: function() {
							var notes = [	{x: "0.5", y:"0.5", note:"AFL Grand Final Trophy"}, 
											{x: "0.322", y:"0.269", note: '\
											<center><b>Brisbane Lions Flag</b><br/>\
											<img src="http://www.lions.com.au/static-resources/themes/brisbane/images/logo-brisbane.png"/></center>\
											<a href="http://www.lions.com.au/" target="blank">The Brisbane Lions</a> \
											is an <a href="http://en.wikipedia.org/wiki/Australian_rules_football" target="blank">Australian rules football club.</a>'
											},
											{x: "0.824", y: "0.593", note: "Fluffy microphone"}];
							this.import(notes);
						}
		});
	});)`

I understand that on image's onReady function, the co-ordinates are getting updated. Now I don't want to update the image everytime, I just need to update the markers. But without reloading the whole page, the marker's are not getting updated. I even posted a question on SO, https://stackoverflow.com/questions/44836498/reload-img-onready-function-again-and-again

Can you please tell me how to do it?

**Comment by waynegm** [comment]
imgNotes2 is a basic example of extending the imgViewer2 plugin. To get your custom behaviour you need to  change the addNote method and save the leaflet marker in a variable so you can update its location later. When you need to change the marker location use the imgViewer2 method relposToLatLng to convert your image coordinate to a  [Leaflet ](http://leafletjs.com/) coordinate and pass that to the markers setLatLng method.

**Comment by waynegm** [comment]
Here is a simple example of deriving a new plugin from imgViewer2 to have a moving marker: [test.zip](https://github.com/waynegm/imgViewer2/files/1190356/test.zip)

While trying this I discovered a bug in the imgViewer2 panTo function which I have fixed and pushed to master.

**Comment by anubhaw2091** [comment]
Thanks a lot.
