### ISSUE TITLE
remove a marker from map 

### ISSUE THREAD

**Issue by softsan** [waynegm/imgViewer2#7]
Hi,

need to remove "marker" from map on mouse click. There are methods to add marker but could not find way for remove "marker". 

Any thoughts?

**Comment by waynegm** [comment]
Leaflet markers inherit a method from Layer called _remove_ which does what you want. Here is a basic hack of the _addNote_ method in the _basic_note.html_ example to demonstrate this:
```
addNote: function(data) {
    var map = this.map,
    loc = this.relposToLatLng(data.x, data.y);
    var marker = L.marker(loc).addTo(map).bindPopup(data.note+"</br><input type='button' value='Delete' class='marker-delete-button'/>");
    marker.on("popupopen", function() {
        var temp = this;
       $(".marker-delete-button:visible").click(function () {
           temp.remove();
       });
    });
}
```

**Comment by softsan** [comment]
Yeh, that did the trick.

Thanks for your quick support and help.
