### ISSUE TITLE
layers

### ISSUE THREAD

**Issue by alessandrooliveroao** [waynegm/imgViewer2#8]
how can I pan and zoom a div with two or more png images with same width, height and position (and scale zoom)? the png images are one above the others like layers.

**Comment by waynegm** [comment]
This functionality is not built in but easy to add by creating your own extension  of the plugin. The underlying Leaflet mapping widget has good support for handling multiple layers.  Have a look at the attached quick hack where I add an extra image layer and use the Leaflet layer control to select which one is visible.
[multiple_image.zip](https://github.com/waynegm/imgViewer2/files/1436554/multiple_image.zip)
